FROM node:20-alpine

RUN apk add --no-cache libc6-compat
RUN corepack enable

WORKDIR /app

COPY pnpm-workspace.yaml .
COPY package.json .
COPY pnpm-lock.yaml .

COPY apps/customer-web ./apps/customer-web
COPY packages ./packages
COPY tsconfig.json .
COPY turbo.json .
COPY tailwind.config.ts .

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/customer-web

RUN pnpm build

EXPOSE 3000

CMD ["pnpm","start"]