FROM node:20-alpine AS base

RUN apk add --no-cache libc6-compat
RUN corepack enable

WORKDIR /app

COPY pnpm-workspace.yaml .
COPY package.json .
COPY pnpm-lock.yaml .

COPY apps/admin-web ./apps/admin-web
COPY packages ./packages
COPY tsconfig.json .
COPY turbo.json .
COPY tailwind.config.ts .

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/admin-web

RUN pnpm build

EXPOSE 3001

CMD ["pnpm","start"]