export enum ReturnReason {
  DAMAGED_PRODUCT = 'DAMAGED_PRODUCT',

  DEFECTIVE_PRODUCT = 'DEFECTIVE_PRODUCT',

  WRONG_ITEM = 'WRONG_ITEM',

  SIZE_ISSUE = 'SIZE_ISSUE',

  QUALITY_ISSUE = 'QUALITY_ISSUE',

  NOT_NEEDED = 'NOT_NEEDED',

  OTHER = 'OTHER',
}