export const ErrorCode = {
  VALIDATION: {
    INVALID_PHONE_NUMBER: 'VALIDATION.INVALID_PHONE_NUMBER',
    INVALID_EMAIL: 'VALIDATION.INVALID_EMAIL',
    INVALID_OTP_FORMAT: 'VALIDATION.INVALID_OTP_FORMAT',
    IDENTIFIER_REQUIRED: 'VALIDATION.IDENTIFIER_REQUIRED',
    GENERIC: 'VALIDATION.GENERIC', // ✅ new generic code for multiple field errors
    INVALID_SLUG: 'VALIDATION.INVALID_SLUG', // ✅ new
    INVALID_CATEGORY_NAME: 'VALIDATION.INVALID_CATEGORY_NAME', // ✅ new
    INVALID_BRAND_NAME: 'VALIDATION.INVALID_BRAND_NAME', // ✅ new
  },

  OTP: {
    INVALID: 'OTP.INVALID', // ✅ unified
    EXPIRED: 'OTP.EXPIRED',
    MAX_ATTEMPTS_EXCEEDED: 'OTP.MAX_ATTEMPTS_EXCEEDED',
    COOLDOWN_ACTIVE: 'OTP.COOLDOWN_ACTIVE', // renamed
    NOT_FOUND: 'OTP.NOT_FOUND',
  },

  RATELIMIT: {
    BLOCKED: 'RATELIMIT.BLOCKED', // renamed (more generic)
  },

  AUTH: {
    GOOGLE_AUTH_FAILED: 'AUTH.GOOGLE_AUTH_FAILED',
    INVALID_TOKEN: 'AUTH.INVALID_TOKEN', // ✅ new
    TOKEN_VERSION_MISMATCH: 'AUTH.TOKEN_VERSION_MISMATCH', // 🔥 important
    FORBIDDEN_ROLE: 'AUTH.FORBIDDEN_ROLE', // ✅ new
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    INVALID_TOTP: 'AUTH.INVALID_TOTP',
  },

  SESSION: {
    EXPIRED: 'SESSION.EXPIRED',
    REVOKED: 'SESSION.REVOKED',
    NOT_FOUND: 'SESSION.NOT_FOUND', // ✅ new unified code
    CANNOT_LOGOUT_CURRENT: 'SESSION.CANNOT_LOGOUT_CURRENT', // ✅ new
    INVALID_ENUM_MAPPING: 'SESSION.INVALID_ENUM_MAPPING',
  },

  USER: {
    NOT_FOUND: 'USER.NOT_FOUND',
    INACTIVE: 'USER.INACTIVE',
  },

  IDENTITY: {
    NOT_FOUND: 'IDENTITY.NOT_FOUND',
    NOT_VERIFIED: 'IDENTITY.NOT_VERIFIED',
    INACTIVE: 'IDENTITY.INACTIVE',
    PASSWORD_MISSING: 'IDENTITY.PASSWORD_MISSING', // ✅ new
    TOTP_NOT_ENABLED: 'IDENTITY.TOTP_NOT_ENABLED', // ✅ new
  },

  CATEGORY: {
    NOT_FOUND: 'CATEGORY.NOT_FOUND',
    SUB_NOT_FOUND: 'CATEGORY.SUB_NOT_FOUND',
    MINI_NOT_FOUND: 'CATEGORY.MINI_NOT_FOUND',
    INACTIVE: 'CATEGORY.INACTIVE',
    INVALID_HIERARCHY: 'CATEGORY.INVALID_HIERARCHY',
    SLUG_EXISTS: 'CATEGORY.SLUG_EXISTS',
    HAS_CHILDREN: 'CATEGORY.HAS_CHILDREN',
  },

  SUB_CATEGORY: {
    NOT_FOUND: 'SUB_CATEGORY.NOT_FOUND',
    INACTIVE: 'SUB_CATEGORY.INACTIVE',
    SLUG_EXISTS: 'SUB_CATEGORY.SLUG_EXISTS',
    HAS_CHILDREN: 'SUB_CATEGORY.HAS_CHILDREN',
  },

  MINI_CATEGORY: {
    NOT_FOUND: 'MINI_CATEGORY.NOT_FOUND',
    INACTIVE: 'MINI_CATEGORY.INACTIVE',
    SLUG_EXISTS: 'MINI_CATEGORY.SLUG_EXISTS',
  },

  BRAND: {
    ALREADY_EXISTS: 'BRAND.ALREADY_EXISTS',
    INVALID: 'BRAND.INVALID',
    NOT_ACTIVE: 'BRAND.NOT_ACTIVE',
    ALREADY_DELETED: 'BRAND.ALREADY_DELETED',
    SLUG_EXISTS: 'BRAND.SLUG_EXISTS',
    NOT_FOUND: 'BRAND.NOT_FOUND',
  },

  PRODUCT: {
    NOT_FOUND: 'PRODUCT.NOT_FOUND',
    SLUG_EXISTS: 'PRODUCT.SLUG_EXISTS',
    INVALID: 'PRODUCT.INVALID',
    INACTIVE: 'PRODUCT.INACTIVE',
    VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  },

  VARIANT: {
    NOT_FOUND: 'VARIANT.NOT_FOUND',
    SKU_EXISTS: 'VARIANT.SKU_EXISTS',
    INVALID: 'VARIANT.INVALID',
    OUT_OF_STOCK: 'VARIANT.OUT_OF_STOCK',
  },

  PRODUCT_IMAGE: {
    NOT_FOUND: 'PRODUCT_IMAGE.NOT_FOUND',
    INVALID_OWNER: 'PRODUCT_IMAGE.INVALID_OWNER',
  },

  PROFILE: {
    NOT_FOUND: 'PROFILE_NOT_FOUND',
    ALREADY_DELETED: 'PROFILE_ALREADY_DELETED',
    ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS: 'PROFILE_EMAIL_ALREADY_EXISTS',
    PHONE_NUMBER_ALREADY_EXISTS: 'PROFILE.PHONE_NUMBER_ALREADY_EXISTS',

    INVALID_EMAIL: 'PROFILE.INVALID_EMAIL',
    INVALID_PHONE_NUMBER: 'PROFILE.INVALID_PHONE_NUMBER',
  },

  SAVED_ADDRESS: {
    NOT_FOUND: 'SAVED_ADDRESS.NOT_FOUND',
    DEFAULT_NOT_FOUND: 'SAVED_ADDRESS.DEFAULT_NOT_FOUND',
    NOT_ACTIVE: 'SAVED_ADDRESS.NOT_ACTIVE',
    ACCESS_DENIED: 'SAVED_ADDRESS.ACCESS_DENIED',
    INVALID_TYPE: 'SAVED_ADDRESS.INVALID_TYPE',
    ALREADY_DELETED: 'SAVED_ADDRESS.ALREADY_DELETED',
    IN_USE: 'ADDRESS_IN_USE',
    HOME_ALREADY_EXISTS: 'SAVED_ADDRESS.HOME_ALREADY_EXISTS',
    WORK_ALREADY_EXISTS: 'SAVED_ADDRESS.WORK_ALREADY_EXISTS',
    INVALID: 'SAVED_ADDRESS.INVALID_ID',
  },

  CART: {
    ALREADY_CONVERTED: 'CART.ALREADY_CONVERTED',
    ALREADY_MERGED: 'CART.ALREADY_MERGED',
    EXPIRED: 'CART.EXPIRED',
    LOCKED: 'CART.LOCKED',
    NOT_FOUND: 'CART.NOT_FOUND',
    ITEM_NOT_FOUND: 'CART.ITEM_NOT_FOUND',
    ITEM_OUT_OF_STOCK: 'CART.ITEM_OUT_OF_STOCK',
    ITEM_ALREADY_EXISTS: 'CART.ITEM_ALREADY_EXISTS',
    INVALID_OPERATION: 'CART.INVALID_OPERATION',
    INVALID_OWNER: 'CART.INVALID_OWNER',
  },

  CHECKOUT_SESSION: {
    NOT_FOUND: 'CHECKOUT_SESSION.NOT_FOUND',
    INVALID: 'CHECKOUT_SESSION.INVALID',
    EXPIRED: 'CHECKOUT_SESSION.EXPIRED',
    ALREADY_COMPLETED: 'CHECKOUT_SESSION.ALREADY_COMPLETED',
  },

  ORDER: {
    NOT_FOUND: 'ORDER.NOT_FOUND',
    ALREADY_COMPLETED: 'ORDER.ALREADY_COMPLETED',
    ALREADY_SHIPPED: 'ORDER.ALREADY_SHIPPED',
    ALREADY_DELIVERED: 'ORDER.ALREADY_DELIVERED',
    PAYMENT_FAILED: 'ORDER.PAYMENT_FAILED',
    CANCELLED: 'ORDER.CANCELLED',
    INVALID_OPERATION: 'ORDER.INVALID_OPERATION',
    SHIPPING_ADDRESS_NOT_FOUND: 'ORDER.SHIPPING_ADDRESS_NOT_FOUND',
    BILLING_ADDRESS_NOT_FOUND: 'ORDER.BILLING_ADDRESS_NOT_FOUND',
    ADDRESS_ACCESS_DENIED: 'ORDER.ADDRESS_ACCESS_DENIED',
    ADDRESS_INACTIVE: 'ORDER.ADDRESS_INACTIVE',
  },

  COUPON: {
    EXPIRED: 'EXPIRED',
    NOT_ACTIVE: 'NOT_ACTIVE',
    NOT_FOUND: 'NOT_FOUND',
    USAGE_LIMIT_REACHED: 'USAGE_LIMIT_REACHED',
    INVALID: 'INVALID',
    MINIMUM_ORDER_NOT_REACHED: 'MINIMUM_ORDER_NOT_REACHED',
    CODE_ALREADY_EXISTS: 'CODE_ALREADY_EXISTS',
  },

  COINS: {
    ALREADY_REDEEMED: 'ALREADY_REDEEMED',
    COINS_EXPIRED: 'COINS_EXPIRED',
    COIN_TRANSACTION_NOT_FOUND: 'COIN_TRANSACTION_NOT_FOUND',
    DUPLICATE_COIN_TRANSACTION: 'DUPLICATE_COIN_TRANSACTION',
    INACTIVE_REWARD_CONFIG: 'INACTIVE_REWARD_CONFIG',
    INSUFFICIENT_COINS: 'INSUFFICIENT_COINS',
    INVALID_COIN_TRANSACTION: 'INVALID_COIN_TRANSACTION',
    INVALID_REDEMPTION: 'INVALID_REDEMPTION',
    INVALID_REFUND_AMOUNT: 'INVALID_REFUND_AMOUNT',
    INVALID_WALLET_QUERY: 'INVALID_WALLET_QUERY',
    NEGATIVE_WALLET_BALANCE: 'NEGATIVE_WALLET_BALANCE',
    REDEMPTION_NOT_FOUND: 'REDEMPTION_NOT_FOUND',
    REDEEMED_TRANSACTION_NOT_FOUND: 'REDEEMED_TRANSACTION_NOT_FOUND',
    COINS_ALREADY_REFUNDED: 'COINS_ALREADY_REFUNDED',
    REWARD_CAMPAIGN_NOT_FOUND: 'REWARD_CAMPAIGN_NOT_FOUND',
    REWARD_CONFIG_NOT_FOUND: 'REWARD_CONFIG_NOT_FOUND',
    REWARD_TIER_NOT_FOUND: 'REWARD_TIER_NOT_FOUND',
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  },

  CUSTOMER: {
    NOT_FOUND: 'CUSTOMER.NOT_FOUND',
  },

  WISHLIST: {
    NOT_FOUND: 'WISHLIST.NOT_FOUND',
    ALREADY_EXISTS: 'WISHLIST.ALREADY_EXISTS',
    PRODUCT_NOT_FOUND: 'WISHLIST.PRODUCT_NOT_FOUND',
  },

  COLLECTION: {
    ALREADY_EXISTS: 'COLLECTION.ALREADY_EXISTS',
    NOT_FOUND: 'COLLECTION.NOT_FOUND',
    INACTIVE: 'COLLECTION.INACTIVE',
    PRODUCT_ALREADY_EXISTS: 'COLLECTION.PRODUCT_ALREADY_EXISTS',
    PRODUCT_NOT_FOUND: 'COLLECTION.PRODUCT_NOT_FOUND',
  },

  BANNER: {
    NOT_FOUND: 'BANNER_NOT_FOUND',
    INACTIVE: 'BANNER_INACTIVE',
    ALREADY_EXISTS: 'BANNER_ALREADY_EXISTS',

    IMAGE_NOT_FOUND: 'BANNER_IMAGE_NOT_FOUND',
    IMAGE_INACTIVE: 'BANNER_IMAGE_INACTIVE',
  },
  SEARCH: {
    INVALID_QUERY: 'INVALID_QUERY',
  },

  RETURN: {
    NOT_FOUND: 'RETURN_NOT_FOUND',
    INVALID_OPERATION: 'RETURN_INVALID_OPERATION',
    ALREADY_REQUESTED: 'RETURN_ALREADY_REQUESTED',
    ALREADY_APPROVED: 'RETURN_ALREADY_APPROVED',
    ALREADY_REJECTED: 'RETURN_ALREADY_REJECTED',
    ALREADY_PICKED_UP: 'RETURN_ALREADY_PICKED_UP',
    ALREADY_COMPLETED: 'RETURN_ALREADY_COMPLETED',
    NOT_APPROVED: 'RETURN_NOT_APPROVED',
    NOT_PICKED_UP: 'RETURN_NOT_PICKED_UP',
  },

  SHIPPING_CONFIGURATION: {
    NOT_FOUND: 'SHIPPING_CONFIGURATION_NOT_FOUND',
    INVALID: 'INVALID_SHIPPING_CONFIGURATION',
    ACTIVE_CANNOT_BE_DELETED: 'ACTIVE_SHIPPING_CONFIGURATION_CANNOT_BE_DELETED',
    AT_LEAST_ONE_ACTIVE_REQUIRED: 'AT_LEAST_ONE_ACTIVE_SHIPPING_CONFIGURATION_REQUIRED',
  },
} as const;
