export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',

  CONFIRMED = 'CONFIRMED',

  PROCESSING = 'PROCESSING',

  SHIPPED = 'SHIPPED',

  DELIVERED = 'DELIVERED',

  CANCELLED = 'CANCELLED',

  REFUNDED = 'REFUNDED',

  RETURNED = 'RETURNED',
}
