export const PLACEHOLDERS = [
  "Medical Equipment & Healthcare Supplies",
  "Surgical Instruments & Operating Room Tools",
  "Diagnostic Kits & Laboratory Testing Equipment",
  "Hospital Furniture & Patient Care Solutions",
  "Advanced Laboratory Equipment & Microscopes",
  "ECG Machines, Monitors & Cardiology Devices",
  "Blood Pressure Monitors & Health Diagnostics",
  "Wheelchairs, Walkers & Rehabilitation Equipment",
  "Oxygen Concentrators & Respiratory Care Devices",
  "Medical Consumables & Daily Clinical Essentials",
  "Healthcare Supplies for Hospitals & Clinics",
  "Dental Equipment & Professional Dental Instruments",
  "ICU Equipment & Critical Patient Monitoring Systems",
  "Physiotherapy Equipment & Rehabilitation Products🦴",
  "Emergency Medical Equipment & First Aid Supplies",
  "Home Healthcare Products & Wellness Essentials",
  "Orthopedic Supports, Braces & Mobility Solutions",
  "Infusion Pumps, Syringes & IV Therapy Equipment",
  "Hospital Beds, Mattresses & Patient Room Equipment",
  "Trusted Medical Brands & Certified Healthcare Products ",
];